//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.WCF.EF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Log
    {
        public int Id { get; set; }
        public string LogLevel { get; set; }
        public string LogTitle { get; set; }
        public string LogDetail { get; set; }
        public System.DateTimeOffset Date { get; set; }
    }
}
