//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.WCF.EF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class TaskLog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTimeOffset CreationDate { get; set; }
        public int TaskId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
